In [1]:
import os
import torch
from torch.utils.data import Dataset, DataLoader
from pyntcloud import PyntCloud
import pickle

In [2]:
import numpy as np
import torch

In [3]:
dataset_path = '/home/yaoliu/scratch/data/modelnet/ModelNet40SampleNorm'

In [4]:
mode= 'test'

In [5]:
category= None
transform= None

In [6]:
        categories_all = [name for name in os.listdir(dataset_path) if name not in ['.DS_Store', 'README.txt']]
        if category:
            if category not in categories_all:
                raise Exception('Categoty not found !')
            categories = [category]
        else:
            categories = categories_all

In [7]:
        categories.sort()
        path_label_pairs = []

In [8]:
        for category in categories:
            label = categories_all.index(category)
            folder_path = os.path.join(dataset_path, category, mode)
            pairs = [(os.path.join(folder_path, name), label) for name in os.listdir(folder_path) if name != '.DS_Store']
            path_label_pairs += pairs

In [10]:
len(path_label_pairs)

2468

In [9]:
    path, label = path_label_pairs[0]
    label = torch.LongTensor([label])
    obj = PyntCloud.from_file(path)
    points = torch.FloatTensor(obj.xyz)

In [11]:
points

tensor([[ 0.1020, -0.0773, -0.0532],
        [ 0.0933,  0.6811, -0.0285],
        [-0.3355,  0.2478, -0.0339],
        ...,
        [ 0.7384, -0.1090,  0.0316],
        [ 0.6998,  0.1606,  0.0335],
        [ 0.0480,  0.6843, -0.0082]])

In [11]:
data=[]

In [14]:

for index in range(2468):
    path, label = path_label_pairs[index]
    label = torch.LongTensor([label])
    obj = PyntCloud.from_file(path)
    points = torch.FloatTensor(obj.xyz)
    # points=rotate(points, 315, 2)
    # if self.transform:
    #     points = self.transform(points)
    points=normal2unit(points)
    data.append([[label],[points]])

In [16]:
len(data)/2468

1.0

In [17]:
import pickle

In [18]:
        f = open('./modelnet40_aug4590_test.cpkl', "wb")
        pickle.dump(data, f, protocol=4)
        f.close()

In [19]:
        f = open('./modelnet40_aug4590.cpkl', "rb")
        loadData = pickle.load(f)
        f.close()

In [20]:
data

[[[tensor([0])],
  [tensor([[ 0.0869, -0.1344, -0.0137],
           [-0.0558,  0.1963,  0.0829],
           [ 0.2925, -0.3270, -0.1035],
           ...,
           [-0.2515, -0.0795, -0.0114],
           [ 0.0545,  0.2020, -0.0154],
           [-0.3341, -0.0512, -0.0201]])]],
 [[tensor([0])],
  [tensor([[-0.0167, -0.5016, -0.0037],
           [-0.0865, -0.1783, -0.1125],
           [-0.1736,  0.0707, -0.0287],
           ...,
           [ 0.0265, -0.1712, -0.0208],
           [ 0.6288,  0.0282, -0.0265],
           [ 0.4899,  0.1412,  0.0185]])]],
 [[tensor([0])],
  [tensor([[ 0.4398, -0.3267, -0.0658],
           [-0.6621, -0.1958, -0.0444],
           [-0.3476, -0.3240, -0.0647],
           ...,
           [ 0.0094, -0.0508,  0.0344],
           [-0.2954, -0.0709, -0.0756],
           [ 0.1000,  0.0161, -0.0312]])]],
 [[tensor([0])],
  [tensor([[-0.1567,  0.6918,  0.0281],
           [ 0.0963, -0.0488, -0.0526],
           [ 0.1585, -0.0796, -0.0795],
           ...,
           [ 0.0

In [19]:
loadData[0][0][0]

tensor([0])

In [28]:
points

tensor([[ 0.1020, -0.0773, -0.0532],
        [ 0.0933,  0.6811, -0.0285],
        [-0.3355,  0.2478, -0.0339],
        ...,
        [ 0.7384, -0.1090,  0.0316],
        [ 0.6998,  0.1606,  0.0335],
        [ 0.0480,  0.6843, -0.0082]])

In [43]:
a=[[[label],[points]],[[label],[points]]]

In [45]:
torch.tensor(a[0][1])

[tensor([[ 0.1020, -0.0773, -0.0532],
         [ 0.0933,  0.6811, -0.0285],
         [-0.3355,  0.2478, -0.0339],
         ...,
         [ 0.7384, -0.1090,  0.0316],
         [ 0.6998,  0.1606,  0.0335],
         [ 0.0480,  0.6843, -0.0082]])]

In [13]:
def normal2unit(vertices: "(vertice_num, 3)"):
    """
    Return: (vertice_num, 3) => normalized into unit sphere
    """
    center = vertices.mean(dim= 0)
    vertices -= center
    distance = vertices.norm(dim= 1)
    vertices /= distance.max()
    return vertices

In [50]:
def rotate(points, degree: float, axis: int):
    """Rotate along upward direction"""
    rotate_matrix = torch.eye(3)
    theta = (degree/360)*2*np.pi
    cos = np.cos(theta)
    sin = np.sin(theta)
    
    axises = [0, 1, 2]
    assert  axis in axises
    axises.remove(axis)

    rotate_matrix[axises[0], axises[0]] = cos
    rotate_matrix[axises[0], axises[1]] = -sin
    rotate_matrix[axises[1], axises[0]] = sin
    rotate_matrix[axises[1], axises[1]] = cos
    points = points @ rotate_matrix
    return points

In [20]:
rotate(points, 180, 2)

tensor([[-0.1020,  0.0773, -0.0532],
        [-0.0933, -0.6811, -0.0285],
        [ 0.3355, -0.2478, -0.0339],
        ...,
        [-0.7384,  0.1090,  0.0316],
        [-0.6998, -0.1606,  0.0335],
        [-0.0480, -0.6843, -0.0082]])